version: '3'
services:
  # edit .env file
  web:
    container_name: internal-${HOST_NAME}
    hostname: internal-${HOST_NAME}
    build: '.'
    volumes:
      - ../public_html/${HOST_NAME}:/home/public_html:rw
      - ../run/main/${HOST_NAME}:/home/run:rw
      - ../run/${HOST_NAME}/postgresql:/run/postgresql:rw
    environment:
      - HOST_NAME=${HOST_NAME}
    restart: unless-stopped # always
  postgresql:
    container_name: internal-postgresql-${HOST_NAME}
    hostname: internal-postgresql-${HOST_NAME}
    build: './postgresql'
    volumes:
      - ../data/${HOST_NAME}/postgresql:/var/lib/postgresql/data:rw
      - ../run/${HOST_NAME}/postgresql:/run/postgresql:rw
    environment:
      - POSTGRES_PASSWORD=postgresql_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=default-db
    restart: unless-stopped # always
    networks:
      - pgadmin
networks:
  pgadmin:
    external:
      name: pgadmin
